try {
    throw ('user not found')
} catch (error) {

    console.log(error)
} finally {

}